# This is a basic workflow to help you get started with Actions

name: Cheat sheet verification
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_with_container:
    runs-on: ubuntu-latest
    container: gcc:4
    steps:
      - name: GCC version
        run: gcc -v
  # NOT WORKING
  # macos_with_container:
  #   runs-on: macos-latest
  #   container: gcc:4
  #   steps:
  #     - name: GCC version
  #       run: gcc -v
  # NOT WORKING
  # windows_with_container:
  #   runs-on: windows-latest
  #   container: gcc:4
  #   steps:
  #     - name: GCC version
  #       run: gcc -v
