# This is a basic workflow to help you get started with Actions

name: Cheat sheet verification
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  macos_with_container:
    # The type of runner that the job will run on
    runs-on: macos-latest
    container: gcc:4
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: GCC version
        run: gcc -v
